name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["🚦 status: awaiting triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: detailed-description
    attributes:
      label: Detailed Description
      description: What's the bug? What did you expect to happen? What actually happened?
      placeholder: A detailed description of the bug report.
      value: "I found this error in this project where ..."
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: How can someone reproduce the behavior?
      description: Steps to reproduce the behavior you were facing.
      placeholder: How can someone reproduce the behavior you were facing?
      value: |
        1. Goto...
        2. Do...
        3. Now...
        4. Finally...
    validations:
        required: true

  - type: input
    id: environment
    attributes:
      label: What was you environment (os, browser, runtime, etc)?
      description: The environment (os, browser, runtime, etc) which faced the bug described
      placeholder: What was environment (os, browser, runtime, etc) while you were facing the issue?
      value: "Ubuntu Latest, Chrome Latest, Node14..."
    validations:
        required: true

  - type: checkboxes
    id: code-of-conduct
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/CeruleanCodersComm/.github/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
    validations:
        required: true

  - type: textarea
    attributes:
        label: Anything else?
        description: |
          Links? References? Anything that will give us more context about the issue you are encountering!
      
          Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
        required: false
