name: Documentation Report
description: File a bug/feature for the documentation
title: "[Docs]: "
labels: ["🚦 status: awaiting triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this issue!

  - type: textarea
    id: detailed-description
    attributes:
      label: Detailed Description
      description: What's the issue? What is the bug/feature for the documentation?
      placeholder: A detailed description of the doc report.
      value: "I think updating the docs at ... with ... will be helpful to ... in ..."
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: Where is the issue (link)?
      description: The link to the page having the issue if it is a bug
      placeholder: "https://github.com/CeruleanCodersComm/.github/blob/main/CODE_OF_CONDUCT.md"
      value: ""
    validations:
        required: false

  - type: checkboxes
    id: code-of-conduct
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/CeruleanCodersComm/.github/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
    validations:
        required: true

  - type: textarea
    attributes:
        label: Anything else?
        description: |
          Links? References? Anything that will give us more context about the issue you are encountering!
      
          Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
        required: false
