name: Feature Request
description: File a feature request
title: "[Feat]: "
labels: ["🚦 status: awaiting triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!

  - type: textarea
    id: detailed-description
    attributes:
      label: Detailed Description
      description: What do you want to be added? How does it help others? Describe the feature
      placeholder: A detailed description of the feature request.
      value: "I found ... in this project which can be improved by adding ..."
    validations:
      required: true

  - type: checkboxes
    id: code-of-conduct
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/CeruleanCodersComm/.github/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
    validations:
        required: true

  - type: textarea
    attributes:
        label: Anything else?
        description: |
          Links? References? Anything that will give us more context about the issue you are encountering!
      
          Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
        required: false
